#!/bin/bash

echo "Quick Setup for VibeBrowser Pitch Deployment"
echo "============================================="
echo ""
echo "Since you already have HomesteadLink deployed, you can reuse the NETLIFY_AUTH_TOKEN"
echo ""
echo "Steps:"
echo "1. Create a new Netlify site at: https://app.netlify.com/teams/Team000/sites/new"
echo "   - Choose 'Import an existing project'"
echo "   - Connect to GitHub and select 'dzianisv/vibebrowser-pitch'"
echo "   - Or drag and drop the index.html file to create a new site"
echo ""
echo "2. Get the Site ID from the new site's settings"
echo ""
echo "3. Run these commands (replace YOUR_SITE_ID):"
echo ""
echo "# Copy the auth token from HomesteadLink (you'll need to get this from GitHub settings)"
echo "# Go to: https://github.com/HomesteadLink/landing/settings/secrets/actions"
echo ""
echo "# Then set both secrets for the new repo:"
echo "gh secret set NETLIFY_AUTH_TOKEN --body 'YOUR_AUTH_TOKEN' --repo dzianisv/vibebrowser-pitch"
echo "gh secret set NETLIFY_SITE_ID --body 'YOUR_SITE_ID' --repo dzianisv/vibebrowser-pitch"
echo ""
echo "4. Configure custom domain in Netlify:"
echo "   - Go to Site Settings > Domain Management"
echo "   - Add custom domain: pitch.vibebrowser.app"